### ISSUE TITLE
Reaping rosco when not enabled fails deployment

### ISSUE THREAD

**Issue by TYsewyn** [spinnaker/halyard#599]
I disabled rosco using a custom service setting file since we don’t use this component.
When running `hal deploy apply --debug` for the first time I get following stacktrace:
```
- Failed to deploy Spinnaker.
com.netflix.spinnaker.halyard.cli.services.v1.ExpectedDaemonFailureException: Failed to deploy Spinnaker.
    at com.netflix.spinnaker.halyard.cli.services.v1.OperationHandler.get(OperationHandler.java:45)
    at com.netflix.spinnaker.halyard.cli.command.v1.AbstractRemoteActionCommand.executeThis(AbstractRemoteActionCommand.java:51)
    at com.netflix.spinnaker.halyard.cli.command.v1.NestableCommand.safeExecuteThis(NestableCommand.java:181)
    at com.netflix.spinnaker.halyard.cli.command.v1.NestableCommand.execute(NestableCommand.java:129)
    at com.netflix.spinnaker.halyard.cli.command.v1.NestableCommand.execute(NestableCommand.java:132)
    at com.netflix.spinnaker.halyard.cli.command.v1.NestableCommand.execute(NestableCommand.java:132)
    at com.netflix.spinnaker.halyard.cli.Main.main(Main.java:47)
Caused by: java.lang.Exception: 404 Not Found
    at retrofit.RetrofitError.httpError(RetrofitError.java:40)
    at retrofit.RestAdapter$RestHandler.invokeRequest(RestAdapter.java:388)
    at retrofit.RestAdapter$RestHandler.invoke(RestAdapter.java:240)
    at com.sun.proxy.$Proxy104.getAllStatus(null)
    at com.netflix.spinnaker.halyard.deploy.deployment.v1.DistributedDeployer.reapRoscoServerGroups(DistributedDeployer.java:247)
    at com.netflix.spinnaker.halyard.deploy.deployment.v1.DistributedDeployer.deploy(DistributedDeployer.java:191)
    at com.netflix.spinnaker.halyard.deploy.deployment.v1.DistributedDeployer.deploy(DistributedDeployer.java:44)
    at com.netflix.spinnaker.halyard.deploy.services.v1.DeployService.deploy(DeployService.java:205)
    at com.netflix.spinnaker.halyard.controllers.v1.DeploymentController.lambda$deploy$16(DeploymentController.java:217)
    at com.netflix.spinnaker.halyard.core.DaemonResponse$StaticRequestBuilder.build(DaemonResponse.java:121)
    at com.netflix.spinnaker.halyard.core.tasks.v1.TaskRepository.lambda$submitTask$1(TaskRepository.java:48)
    at java.lang.Thread.run(Thread.java:745)
```

This step should be skipped when rosco isn't enabled. Ofcourse, this should be executed when rosco was running and is disabled afterwards. I guess this should be possible because you have a list of made changes.
This will also be an issue when reaping orca if this component has been disabled.
I'm not sure why you would do that though, so maybe it is easier to skip this custom service setting for orca?

**Comment by lwander** [comment]
Good catch - I'm thinking it should still reap rosco in case you've disabled it after having run it, and the 404 should instead be treated as a success, WDYT?

**Comment by lwander** [comment]
https://github.com/spinnaker/halyard/pull/601
