### ISSUE TITLE
Could not parse connection information from:

### ISSUE THREAD

**Issue by joshughes** [spinnaker/halyard#618]
During `hal deploy apply` I get the following error. 

My setup is GCE and I have had success getting some configuration pushed up and `hal deploy connect` seems to be working. I am not sure why I am running into this error. 

Bootstrap comes up but when it goes to actually do the deployment of the services... things seem to go south. 

Thanks

```
2017-07-21 12:49:34.182  INFO 1143 --- [       Thread-5] c.n.s.h.core.tasks.v1.TaskRepository     : Task [Apply deployment] (e744407e-85de-41ba-8483-b96adb2acde8) - RUNNING failed with HalException:

com.netflix.spinnaker.halyard.core.error.v1.HalException: Could not parse connection information from:
()
	at com.netflix.spinnaker.halyard.core.tasks.v1.DaemonTaskHandler.lambda$reduceChildren$0(DaemonTaskHandler.java:59)
	at java.util.stream.ReduceOps$1ReducingSink.accept(ReduceOps.java:80)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.reduce(ReferencePipeline.java:484)
	at com.netflix.spinnaker.halyard.core.tasks.v1.DaemonTaskHandler.reduceChildren(DaemonTaskHandler.java:41)
	at com.netflix.spinnaker.halyard.deploy.deployment.v1.DistributedDeployer.deploy(DistributedDeployer.java:189)
	at com.netflix.spinnaker.halyard.deploy.deployment.v1.DistributedDeployer.deploy(DistributedDeployer.java:46)
	at com.netflix.spinnaker.halyard.deploy.services.v1.DeployService.deploy(DeployService.java:205)
	at com.netflix.spinnaker.halyard.controllers.v1.DeploymentController.lambda$deploy$16(DeploymentController.java:217)
	at com.netflix.spinnaker.halyard.core.DaemonResponse$StaticRequestBuilder.build(DaemonResponse.java:121)
	at com.netflix.spinnaker.halyard.core.tasks.v1.TaskRepository.lambda$submitTask$1(TaskRepository.java:48)
	at java.lang.Thread.run(Thread.java:745)

```

**Comment by lwander** [comment]
After our conversation in slack it seems restarting the deployment fixed this. 

If anyone sees this bug, please provide the following info:

`kubectl version`

and given the name of the orca pod (retrieved via `kubectl get po -n spinnaker | grep orca-bootstrap | awk '{print $1}'`), please try to run

`kubectl port-forward $(kubectl get po -n spinnaker | grep orca-bootstrap | awk '{print $1}') 8083:8083 -n spinnaker`
