### ISSUE TITLE
Race condition between front50 and fiat?

### ISSUE THREAD

**Issue by philchristensen** [spinnaker/halyard#675]
I'm using halyard to install Spinnaker onto an AWS-hosted Kubernetes cluster. The initial install went great, but now I'm trying to install/configure Spinnaker with LDAP authentication.

I started by following [these directions](https://www.spinnaker.io/setup/security/authentication/ldap/) and created a file in `.hal/default/profiles/gate-local.yml` with the following contents:

```
ldap:
  enabled: true
  url: ldaps://hub-dc1.aws.logicworks.local:636/DC=us,DC=logicworks,DC=net
  userDnPattern: sAMAccountName={0},OU=Users,OU=Logicworks
```

This seemed odd to me since there was no password information included, but I don't think things are even getting that far before failing.

I also set the following values in `.hal/config`:

- `deploymentConfigurations[0].features.auth=true`
- `deploymentConfigurations[0].features.fiat=true`
- `deploymentConfigurations[0].security.authn.enabled=true`
- `deploymentConfigurations[0].security.authz.enabled=true`

When I apply the deployment, though, I end up with all the containers successfully starting except for fiat, which seems to fail when trying to connect to front50:

```
2017-08-23 20:14:52.231  WARN 1 --- [ecutionAction-1] c.n.s.fiat.roles.UserRolesSyncer         : [] 
User permission sync failed. Server status is DOWN. Trying again in 10000 ms. Cause:(Provider: 
DefaultServiceAccountProvider) retrofit.RetrofitError: 404 Not Found
2017-08-23 20:15:02.255  WARN 1 --- [ront50Service-4] c.n.s.f.p.internal.Front50Service        : [] 
Falling back to service account cache. Cause: 404 Not Found
```

However, the only error I see in the front50 logs is the failure to connect to fiat!

```
2017-08-23 20:14:36.121  INFO 1 --- [0.0-8080-exec-1] o.a.c.c.C.[Tomcat].[localhost].[/]       : 
Initializing Spring FrameworkServlet 'dispatcherServlet'
2017-08-23 20:14:36.121  INFO 1 --- [0.0-8080-exec-1] o.s.web.servlet.DispatcherServlet        : 
FrameworkServlet 'dispatcherServlet': initialization started
2017-08-23 20:14:36.229  INFO 1 --- [0.0-8080-exec-1] o.s.web.servlet.DispatcherServlet        : 
FrameworkServlet 'dispatcherServlet': initialization completed in 107 ms
2017-08-23 20:15:29.191  INFO 1 --- [.0-8080-exec-10] c.n.spinnaker.fiat.shared.FiatService    : ---
> HTTP GET http://spin-fiat.spinnaker:7003/authorize/anonymous
2017-08-23 20:15:44.364  INFO 1 --- [.0-8080-exec-10] c.n.spinnaker.fiat.shared.FiatService    : --
-- ERROR http://spin-fiat.spinnaker:7003/authorize/anonymous
2017-08-23 20:15:44.365  INFO 1 --- [.0-8080-exec-10] c.n.spinnaker.fiat.shared.FiatService    : 
java.net.SocketTimeoutException: connect timed out
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at com.squareup.okhttp.internal.Platform.connectSocket(Platform.java:101)
	at com.squareup.okhttp.internal.io.RealConnection.connectSocket(RealConnection.java:137)
	at com.squareup.okhttp.internal.io.RealConnection.connect(RealConnection.java:108)
```

I'd greatly appreciate any info towards resolving this issue.

**Comment by lwander** [comment]
Thanks for the detailed report - @ttomsu is the expert on this, let's see if he can weigh in

**Comment by ttomsu** [comment]
It's not so much as a race condition as it is a circular dependency. Front50 can startup without Fiat, but can't serve requests for protected resources. Fiat cannot start up successfully without connecting to Front50 (and Clouddriver for that matter)

The curious part is the 404 from front50. That must means it's up - What is your storage provider? Redis as a Front50 storage provider is not (yet) supported, so if that's the case, you'll need to switch to (likely) S3 or another cloud-based storage.

**Comment by philchristensen** [comment]
Aha, that must be it, I haven't configured S3 storage yet, but I was going to. I'll try that.

**Comment by philchristensen** [comment]
That was exactly the problem, after setting up S3 storage everything started working properly.
