### ISSUE TITLE
NullPointerException generating config during `hal deploy apply`

### ISSUE THREAD

**Issue by greenkiwi** [spinnaker/halyard#731]
When I attempt to run `hal deploy apply` I get the following NPE
```
hal_1  | 2017-10-17 05:59:49.891  INFO 7 --- [       Thread-6] c.n.s.h.d.s.v.s.SpinnakerServiceProvider : Building service settings entry for spin-redis
hal_1  | 2017-10-17 05:59:49.907  INFO 7 --- [       Thread-6] c.n.s.h.d.s.v1.service.SpinnakerService  : Reading user provided service settings from /root/.hal/default/service-settings/redis.yml
hal_1  | 2017-10-17 05:59:49.926 ERROR 7 --- [       Thread-6] c.n.s.halyard.core.DaemonResponse        : Unknown exception encountered:
hal_1  |
hal_1  | java.lang.NullPointerException: null
hal_1  | 	at com.netflix.spinnaker.halyard.deploy.spinnaker.v1.service.SpinnakerServiceProvider.buildRuntimeSettings(SpinnakerServiceProvider.java:43) ~[halyard-deploy-0.35.0-20171002192634.jar:0.35.0-20171002192634]
hal_1  | 	at com.netflix.spinnaker.halyard.deploy.services.v1.GenerateService.generateConfig(GenerateService.java:95) ~[halyard-deploy-0.35.0-20171002192634.jar:0.35.0-20171002192634]
hal_1  | 	at com.netflix.spinnaker.halyard.deploy.services.v1.DeployService.deploy(DeployService.java:193) ~[halyard-deploy-0.35.0-20171002192634.jar:0.35.0-20171002192634]
hal_1  | 	at com.netflix.spinnaker.halyard.controllers.v1.DeploymentController.lambda$deploy$16(DeploymentController.java:205) ~[halyard-web-0.35.0-20171002192634.jar:0.35.0-20171002192634]
hal_1  | 	at com.netflix.spinnaker.halyard.core.DaemonResponse$StaticRequestBuilder.build(DaemonResponse.java:125) ~[halyard-core-0.35.0-20171002192634.jar:0.35.0-20171002192634]
hal_1  | 	at com.netflix.spinnaker.halyard.core.tasks.v1.TaskRepository.lambda$submitTask$1(TaskRepository.java:48) ~[halyard-core-0.35.0-20171002192634.jar:0.35.0-20171002192634]
hal_1  | 	at java.lang.Thread.run(Thread.java:745) ~[na:1.8.0_111]
hal_1  |
hal_1  | 2017-10-17 05:59:49.928  WARN 7 --- [       Thread-6] c.n.s.h.core.tasks.v1.TaskRepository     : Task [Apply deployment] (1a3a7bb9-8304-4d4d-b811-fc942080a031) - RUNNING failed with unexpected reason:
hal_1  |
hal_1  | java.lang.NullPointerException: null
hal_1  | 	at com.netflix.spinnaker.halyard.deploy.spinnaker.v1.service.SpinnakerServiceProvider.buildRuntimeSettings(SpinnakerServiceProvider.java:43) ~[halyard-deploy-0.35.0-20171002192634.jar:0.35.0-20171002192634]
hal_1  | 	at com.netflix.spinnaker.halyard.deploy.services.v1.GenerateService.generateConfig(GenerateService.java:95) ~[halyard-deploy-0.35.0-20171002192634.jar:0.35.0-20171002192634]
hal_1  | 	at com.netflix.spinnaker.halyard.deploy.services.v1.DeployService.deploy(DeployService.java:193) ~[halyard-deploy-0.35.0-20171002192634.jar:0.35.0-20171002192634]
hal_1  | 	at com.netflix.spinnaker.halyard.controllers.v1.DeploymentController.lambda$deploy$16(DeploymentController.java:205) ~[halyard-web-0.35.0-20171002192634.jar:0.35.0-20171002192634]
hal_1  | 	at com.netflix.spinnaker.halyard.core.DaemonResponse$StaticRequestBuilder.build(DaemonResponse.java:125) ~[halyard-core-0.35.0-20171002192634.jar:0.35.0-20171002192634]
hal_1  | 	at com.netflix.spinnaker.halyard.core.tasks.v1.TaskRepository.lambda$submitTask$1(TaskRepository.java:48) ~[halyard-core-0.35.0-20171002192634.jar:0.35.0-20171002192634]
hal_1  | 	at java.lang.Thread.run(Thread.java:745) ~[na:1.8.0_111]
hal_1  |
hal_1  | 2017-10-17 05:59:49.931  INFO 7 --- [       Thread-6] c.n.s.halyard.core.tasks.v1.DaemonTask   : [Apply deployment] (1a3a7bb9-8304-4d4d-b811-fc942080a031) - FAILED killing all jobs created by this task
hal_1  | 2017-10-17 05:59:49.931  INFO 7 --- [       Thread-6] c.n.s.h.core.tasks.v1.TaskRepository     : Task [Apply deployment] (1a3a7bb9-8304-4d4d-b811-fc942080a031) - FAILED completed
```

```
hal -v
0.35.0-20171002192634
```

Spinnaker version 1.4.2

Prior to this, I was attempting to get redis working when connecting to an external ElastiCache Redis cluster.  I had changed some of the settings and the file names from `<service>.yml` to `<service>-local.yml`

In the end, I reverted everything and attempted to redeploy and it failed.

**Comment by greenkiwi** [comment]
Ah, I think that I might have determined the cause.  When I reverted, I left the following file: `hal/default/service-settings/redis.yml` simply empty.

**Comment by lwander** [comment]
Ah still seems like a bug - thanks for narrowing down the cause.
